#ifndef KEYPAD_H_
#define	KEYPAD_H_

#define KEYPAD_ROW1       LATCbits.LATC1
#define KEYPAD_ROW1_TRIS  TRISCbits.TRISC1
#define KEYPAD_ROW1_ODC   ODCCbits.ODCC1
#define KEYPAD_ROW1_ANSEL -1

#define KEYPAD_ROW2       LATEbits.LATE0
#define KEYPAD_ROW2_TRIS  TRISEbits.TRISE0
#define KEYPAD_ROW2_ODC   ODCEbits.ODCE0
#define KEYPAD_ROW2_ANSEL -1

#define KEYPAD_ROW3       LATCbits.LATC4
#define KEYPAD_ROW3_TRIS  TRISCbits.TRISC4
#define KEYPAD_ROW3_ODC   ODCEbits.ODCE4
#define KEYPAD_ROW3_ANSEL -1

#define KEYPAD_ROW4       LATDbits.LATD10
#define KEYPAD_ROW4_TRIS  TRISDbits.TRISD10
#define KEYPAD_ROW4_ODC   ODCDbits.ODCD10
#define KEYPAD_ROW4_ANSEL -1

#define KEYPAD_COL1       PORTEbits.RE4
#define KEYPAD_COL1_TRIS  TRISEbits.TRISE4
#define KEYPAD_COL1_CNPU  CNPUEbits.CNPUE4
#define KEYPAD_COL1_ANSEL ANSELEbits.ANSE4

#define KEYPAD_COL2       PORTEbits.RE2
#define KEYPAD_COL2_TRIS  TRISEbits.TRISE2
#define KEYPAD_COL2_CNPU  CNPUEbits.CNPUE2
#define KEYPAD_COL2_ANSEL ANSELEbits.ANSE2

#define KEYPAD_COL3       PORTEbits.RE6
#define KEYPAD_COL3_TRIS  TRISEbits.TRISE6
#define KEYPAD_COL3_CNPU  CNPUEbits.CNPUE6
#define KEYPAD_COL3_ANSEL ANSELEbits.ANSE6

#define TRIS_OUTPUT 0
#define TRIS_INPUT 1

#define ODC_ACTIVE 1

#define CNPU_ENABLE 1

#define ODC_ENABLE 1
#define ODU_DISABLE 0

void KeyPad_Init(void);
char KeyPad_Scan(void);

#endif	/* KEYPAD_H */